# -*- coding: utf-8 -*-
"""exercise5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uJtml_IXAFdOF9ajrvm-bOTmG9b1vO92
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.simplefilter("ignore", DeprecationWarning)
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
import seaborn as sns
data = load_digits()
X,y = data.data,data.target
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
print("training data")
print(x_train)
print("testing data")
print(x_test)
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)
svm_model = SVC(kernel='linear',max_iter=500,probability=True)
svm_model.fit(x_train_scaled,y_train)
y_pred_svm = svm_model.predict(x_test_scaled)
svm_accuracy = accuracy_score(y_test,y_pred_svm)
print("SVM model accuracy",svm_accuracy)
print("svm classification report:")
print(classification_report(y_test,y_pred_svm))
print("svm confusion matrix:")
print(confusion_matrix(y_test,y_pred_svm))
logistic_model = LogisticRegression(max_iter=500)
logistic_model.fit(x_train_scaled,y_train)
y_pred_logistic = logistic_model.predict(x_test_scaled)
logistic_accuracy = accuracy_score(y_test,y_pred_logistic)
print("logistic regression model accuracy",logistic_accuracy)
print("logistic regression classification report:")
print(classification_report(y_test,y_pred_logistic))
print("logistic regression confusion matrix:")
print(confusion_matrix(y_test,y_pred_logistic))
print("learned model weight:")
print(logistic_model.coef_)
print("comparison of models:")
print(f'SVM accuracy: {svm_accuracy},logistic regression accuracy:{logistic_accuracy}')
feature_importance = np.abs(logistic_model.coef_).mean(axis=0)
sns.barplot(x=np.arange(len(feature_importance)),y=feature_importance)
plt.xlabel("feature_index")
plt.ylabel("importance")
plt.title("feature importance in logistic regression")
plt.show()